  sudo: required
  services:
    - docker

before_install:
  - docker build -t tux1980/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t tux1980/server-test -f ./server/Dockerfile.dev ./server


script:
  - docker run tux1980/react-test npm test -- --coverage

after_success:
  - docker build -t tux1980/multi-client ./client
  - docker build -t tux1980/multi-server ./server
  - docker build -t tux1980/multi-worker ./worker
  - docker build -t tux1980/multi-nginx ./nginx

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Now take those fucking images and just push them to Docker-Hub
  - docker push tux1980/multi-client
  - docker push tux1980/multi-server
  - docker push tux1980/multi-worker
  - docker push tux1980/multi-nginx  


#deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-wolli-react"
#   env: "DockerWolliReact-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-295502365329"
#   bicket_path: "docker-wolli-react"
#   on:
#     branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#      secure: $AWS_SECRET_KEY"
